<?php 
require_once dirname(__FILE__).'/system/autoload.inc';
require_once dirname(__FILE__).'/font_awesome4/autoload.inc';
require_once dirname(__FILE__).'/flexslider/autoload.inc';
require_once dirname(__FILE__).'/ts3/autoload.inc';
require_once dirname(__FILE__).'/handlebars/autoload.inc';
require_once dirname(__FILE__).'/wow_tooltips/autoload.inc';
require_once dirname(__FILE__).'/bootstrap3/autoload.inc';