<?php
require_once dirname(__FILE__).'/saimod_mojotrollz_vote/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_downloads/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_servers/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_server_tbc/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_server_classic/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_teamspeak/autoload.inc';
require_once dirname(__FILE__).'/saimod_webcraft_updates/autoload.inc';
require_once dirname(__FILE__).'/saimod_mojotrollz_npc_vendor_template/autoload.inc';

//require_once dirname(__FILE__).'/saimod_mojotrollz_beta/autoload.inc';