<?php
\SYSTEM\autoload::registerFolder(dirname(__FILE__),'');
require_once dirname(__FILE__).'/default_page/autoload.inc';
require_once dirname(__FILE__).'/default_start/autoload.inc';
require_once dirname(__FILE__).'/default_impressum/autoload.inc';
require_once dirname(__FILE__).'/default_account/autoload.inc';
require_once dirname(__FILE__).'/default_serverlist/autoload.inc';
require_once dirname(__FILE__).'/default_beta/autoload.inc';
require_once dirname(__FILE__).'/default_article/autoload.inc';
require_once dirname(__FILE__).'/default_donate/autoload.inc';
require_once dirname(__FILE__).'/default_register/autoload.inc';