<?php
\SYSTEM\autoload::registerFolder(dirname(__FILE__),'');
require_once dirname(__FILE__).'/default_page/autoload.inc';
require_once dirname(__FILE__).'/default_start/autoload.inc';
require_once dirname(__FILE__).'/default_impressum/autoload.inc';
require_once dirname(__FILE__).'/default_account/autoload.inc';
require_once dirname(__FILE__).'/default_serverlist/autoload.inc';
require_once dirname(__FILE__).'/default_beta/autoload.inc';
require_once dirname(__FILE__).'/default_article/autoload.inc';
require_once dirname(__FILE__).'/default_donate/autoload.inc';
require_once dirname(__FILE__).'/default_register/autoload.inc';
require_once dirname(__FILE__).'/default_resetpassword/autoload.inc';

require_once dirname(__FILE__).'/account_website/autoload.inc';
require_once dirname(__FILE__).'/account_changepassword/autoload.inc';
require_once dirname(__FILE__).'/account_changeemail/autoload.inc';

require_once dirname(__FILE__).'/account_tbc/autoload.inc';
require_once dirname(__FILE__).'/account_tbc_new/autoload.inc';